In [1]:
print("Python")

Python


In [2]:
import pandas as pd

In [3]:
import numpy as np

In [6]:
L = list(range(0,10,2)) #start_index, end_index, step_size

In [7]:
L

[0, 2, 4, 6, 8]

In [8]:
print(type(L))

<class 'list'>


In [ ]:
# NumPy Aray

# hOMOGENEOUS DATA(Same Data Type)
#faster
#lower memory
# Vectorized Operized
# MultiDimnsional
#

In [13]:
np_array = np.array(L)

In [14]:
print(type(np_array))

<class 'numpy.ndarray'>


In [15]:
import time

In [16]:
size = 10 ** 6

In [18]:
py_list = list(range(size))

In [20]:
np_arr = np.arange(size)

In [22]:
fruits = ["apple","banana","cherry"]
new_list = []

for fr in fruits:
  if "a" in fr:
    new_list.append(fr)


In [23]:
new_list = [expression for member in iterable if conditional]

['apple', 'banana']

In [24]:
newlist = [fr for fr in fruits if "a" in fr]

In [25]:
newlist

['apple', 'banana']

In [27]:
start = time.time()
py_list = [ x*2 for x in py_list]
print("List Time Taken:", time.time() - start)

List Time Taken: 0.11798095703125


In [28]:
start = time.time()
np_arr = np_arr * 2
print("List Time Taken:", time.time() - start)

List Time Taken: 0.005644559860229492


In [29]:
# 1D Array

In [30]:
arr = np.array([1,2,3,4,5])

In [33]:
arr.shape # 1D  array but it has 5 elements

(5,)

In [34]:
matrix = np.array([[1,2,3],[4,5,6]])

In [35]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
matrix.shape

(2, 3)

In [37]:
tensor = np.array([
    [
        [1,2],
        [3,4],
    ],
     [
         [5,6],
         [7,8]
      ]

])

In [38]:
tensor.shape

(2, 2, 2)

In [41]:
A = np.array([[1,2,3],[4,5,6]])

In [42]:
B =  np.array([[10,20,30],[40,50,60]])

In [43]:
A+B

array([[11, 22, 33],
       [44, 55, 66]])

In [45]:
A = np.array([[1,2,3],[4,5,6]])
B =  np.array([[10,20,30]])

In [46]:
A+B

array([[11, 22, 33],
       [14, 25, 36]])

In [47]:
A = np.array([[1,2,3],[4,5,6]])
B =  np.array([[10], [20]])

In [48]:
A+B

array([[11, 12, 13],
       [24, 25, 26]])

In [51]:
A = np.array([
    [[1,2,3], [4,5,6]],
     [[7,8,9],[10,11,12]]
])

B = np.array([

              [[10,20,30],[40,50,60],
               ],
              [[70,80,90],[100,110,120
              ]]


              ])

In [52]:
A+B

array([[[ 11,  22,  33],
        [ 44,  55,  66]],

       [[ 77,  88,  99],
        [110, 121, 132]]])

In [53]:
zero = np.zeros((3,3))

In [54]:
zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [55]:
np.random.rand(3,3)

array([[0.95466148, 0.93091173, 0.18394958],
       [0.765618  , 0.79117583, 0.06353706],
       [0.9793992 , 0.75390881, 0.27077953]])

In [57]:
x = np.array([10,20,30,40,50])

In [58]:
x[-1]

50

In [ ]:
matrix = np.array([[1,2,3],[4,5,6]]) #3

In [60]:
matrix[0,2]

3

In [61]:
matrix[1,2]

6

In [62]:
#[2,3]'
matrix[0,1:]

array([2, 3])

In [63]:
tensor = np.array([
    [
        [1,2,3],
        [4,5,6],
    ],
     [
         [7,8,9],
         [10,11,12]
      ]

])

In [64]:
#Output -> 6
tensor[0,1,2]

6

In [ ]:
[[7,8],
 [10,11]]

In [67]:
tensor[1,: , 0:2]

array([[ 7,  8],
       [10, 11]])